// Display artwork is separate from the platform edition cover.
const gameMedia = {
  "X-Men Origins: Wolverine": {"poster":"assets/art/wolverine-hero.jpg","artwork":"assets/art/wolverine-hero.jpg","posterPosition":"35% center","coverPlatform":"PS3","trailer":"https://youtu.be/EzG6h_YKHbU?is=jAX-MrKmwOMjh1sc"},
  "Resident Evil HD Remaster": {"poster":"assets/art/resident-evil-hd-poster.jpg","artwork":"assets/art/resident-evil-hd-hero.jpg","posterPosition":"50% center","coverPlatform":"PC","logo":"assets/art/resident-evil-hd-logo.png"},
  "Resident Evil Village": {"poster":"assets/art/resident-evil-village-poster.jpg","artwork":"assets/art/resident-evil-village-hero.jpg","posterPosition":"50% center","coverPlatform":"PS5"},
  "Remember Me": {"poster":"assets/art/remember-me-poster.jpg","artwork":"assets/art/remember-me-hero.jpg","posterPosition":"50% center","coverPlatform":"PC"},
  "Resident Evil 0 HD Remaster": {"poster":"assets/art/resident-evil-0-poster.jpg","artwork":"assets/art/resident-evil-0-hero.jpg","posterPosition":"50% center","coverPlatform":"PC"},
  "Resident Evil 2": {"poster":"assets/art/resident-evil-2-poster.jpg","artwork":"assets/art/resident-evil-2-hero.jpg","posterPosition":"50% center","coverPlatform":"PS5"},
  "Resident Evil 3": {"poster":"assets/art/resident-evil-3-poster.jpg","artwork":"assets/art/resident-evil-3-hero.jpg","posterPosition":"50% center","coverPlatform":"PS5"},
  "Resident Evil Code: Veronica": {"poster":"assets/art/veronica-poster.jpg","posterFit":"contain","artwork":"assets/art/veronica-hero.jpg","posterPosition":"50% center","coverPlatform":"PS3 · HD"},
  "Resident Evil 4": {"poster":"assets/art/resident-evil-4-poster.jpg","artwork":"assets/art/resident-evil-4-hero.jpg","posterPosition":"50% center","coverPlatform":"PS5"},
  "Resident Evil 5": {"poster":"assets/art/resident-evil-5-poster.jpg","artwork":"assets/art/resident-evil-5-hero.jpg","posterPosition":"50% center","coverPlatform":"PS4"},
  "Resident Evil 6": {"poster":"assets/art/resident-evil-6-poster.jpg","artwork":"assets/art/resident-evil-6-hero.jpg","posterPosition":"50% center","coverPlatform":"PS4"},
  "Resident Evil 7 biohazard": {"poster":"assets/art/resident-evil-7-poster.jpg","artwork":"assets/art/resident-evil-7-hero.jpg","posterPosition":"50% center","coverPlatform":"PS5"},
  "Resident Evil Revelations": {"poster":"assets/art/revelations-poster.jpg","artwork":"assets/art/revelations-hero.jpg","posterPosition":"50% center","coverPlatform":"PS4"},
  "Resident Evil Revelations 2": {"poster":"assets/art/revelations-2-poster.jpg","artwork":"assets/art/revelations-2-hero.jpg","posterPosition":"50% center","coverPlatform":"PS4"},
  "Resident Evil Outbreak": {"poster":"assets/art/outbreak-hero.jpg","artwork":"assets/art/outbreak-hero.jpg","posterPosition":"50% center","coverPlatform":"PS2","artworkPosition":"center 30%"},
  "Resident Evil Outbreak File #2": {"poster":"assets/art/outbreak-2-official.jpg","artwork":"assets/art/outbreak-2-official.jpg","posterPosition":"50% center","coverPlatform":"PS2","posterScale":1.18},
  "Resident Evil: Umbrella Chronicles": {"poster":"assets/art/umbrella-hero.jpg","artwork":"assets/art/umbrella-hero.jpg","posterPosition":"50% center","coverPlatform":"Wii","artworkPosition":"center 30%"},
  "Resident Evil: The Darkside Chronicles": {"poster":"assets/art/darkside-hero.jpg","artwork":"assets/art/darkside-hero.jpg","posterPosition":"50% center","coverPlatform":"Wii","artworkPosition":"center 30%"},
  "Deadpool": {"poster":"assets/art/deadpool-hero.jpg","artwork":"assets/art/deadpool-hero.jpg","posterPosition":"85% center","coverPlatform":"PS3"},
  "inFamous": {"poster":"assets/art/infamous-poster.jpg","artwork":"assets/art/infamous-hero.jpg","posterPosition":"50% center","coverPlatform":"PS3"},
  "Transformers: Devastation": {"poster":"assets/art/transformers-hero.jpg","artwork":"assets/art/transformers-hero.jpg","posterPosition":"65% center","coverPlatform":"PS3"},
  "Ninja Blade": {"poster":"assets/art/ninja-blade-hero.jpg","artwork":"assets/art/ninja-blade-hero.jpg","posterPosition":"85% center","coverPlatform":"Xbox 360"},
  "Jak X: Combat Racing": {"poster":"assets/art/jak-x-poster.jpg","artwork":"assets/art/jak-x-poster.jpg","posterPosition":"85% center","coverPlatform":"PS2"},
  "Daxter": {"poster":"assets/art/daxter-hero.jpeg","artwork":"assets/art/daxter-hero.jpeg","posterPosition":"80% center","coverPlatform":"PSP"},
  "Chaos Legion": {"poster":"assets/art/chaos-legion-banner.jpeg","artwork":"assets/covers/chaos-legion-poster.jpeg","posterPosition":"50% center","artworkPosition":"center 35%","cover":"assets/covers/chaos-legion-cover-ps2.jpeg","coverPlatform":"PS2"},
  "CY Girls": {"poster":"assets/covers/cy-girls-poster.jpeg","artwork":"assets/covers/cy-girls-banner.jpeg","posterPosition":"50% center","artworkPosition":"center","cover":"assets/covers/cy-girls-cover-ps2.jpeg","coverPlatform":"PS2"},
  "Phantom Blade Zero": {"poster":"https://image.api.playstation.com/vulcan/ap/rnd/202512/1205/0548e61cb6fb0ff6a6dde647c125569454acf567dd4684f8.png","artwork":"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4115450/b7956f90da7ba6590eb97494b092dc38341fa21c/page_bg_raw.jpg?t=1780448722","posterPosition":"50% center","artworkPosition":"center","cover":"https://image.api.playstation.com/vulcan/ap/rnd/202607/2809/c8c7fe63c265350da094a3b7ba4637f257f172dc68db1589.png","coverPlatform":"PS5 • Digital Deluxe","trailer":"https://www.youtube.com/watch?v=blh1v1dGJ2s"}
};
